language: python

python:
 - "3.5"

install:
 - sudo apt-get update
 - sudo apt-get install swig libsasl2-dev libssl-dev libpq-dev
 - sudo apt-get install openjdk-8-jdk dejagnu checkstyle gcj-jdk
 - sudo apt-get install r-base
 - sudo apt-get install libcunit1-dev libcppunit-dev
 - pip install -r requirements.txt
 - pip freeze
 - python --version && python -c "import sqlite3; print(\"... uses pysqlite \" + sqlite3.version +\" with SQLite \" + sqlite3.sqlite_version);"

script:
 - mkdir ../debug-data
 - mkdir ../test-data
 - ./src/manage-test.py test accounts attestation checker configuration solutions tasks hbrs_tests
